[package]
name = "pp_terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm   = "0.24"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
rustyline   = "11.0"
dirs        = "5.0"
whoami      = "1.4"
chrono      = "0.4"
